# RG params
rg_name: ansible_RG
location: 'Southeast Asia'

# Vnet Details
vnet_name: minio-vnet
vnet_tag: Minio-Vnet
address_prefixes_cidr:
      - "10.0.0.0/16"
      - "172.100.0.0/16"
dns_servers:
      - "127.0.0.1"
      - "127.0.0.2"

# Subnet
subnet_name: minio-subnet
address_subnet_prefix: "10.0.1.0/24" 

# Public IP Details
public_ip_name: "minio_ip"

# Network Security Group
nsg_name: "minio-nsg"

# Network interface
nic_name: vmnic


# VM1 Params
vm1_name: minioNode1
vm1_size: "Standard_B1s"
admin_username: "minioadmin"
admin_password: "Singtel2024*1q2w3e4r/"
virtualMachine1Zone: "1"
tag: "MinIO Nodes" 