---
- name: Create Azure Resource Group
  hosts: localhost
  connection: local
  collections:
    - azure.azcollection

  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: ansible_RG
        location: southeastasia
      register: rg_result

    - name: Debug output
      debug:
        msg: "{{ rg_result }}"
