- name: Create virtual network
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: "{{ rg_name }}"
    api_profile: latest
    name: "{{ vnet_name }}"
    address_prefixes_cidr: "{{ address_prefixes_cidr }}"
    dns_servers: "{{ dns_servers }}"
    tags:
      testing: "{{ vnet_tag }}"