- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: '{{ rg_name:}}'
    name: '{{ nsg_name }}'
    rules:
      - name: 'allow_ssh'
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 100
        direction: Inbound
      
      # - name: 'allow_rdp'
      #   protocol: Tcp
      #   destination_port_range: 3389
      #   access: Allow
      #   priority: 1001
      #   direction: Inbound
    
      # - name: 'allow_web_traffic'
      #   protocol: Tcp
      #   destination_port_range:
      #     - 80
      #     - 443
      #   access: Allow
      #   priority: 1002
      #   direction: Inbound
    
      # - name: 'allow_powershell_remoting'
      #   protocol: Tcp
      #   destination_port_range: 
      #     - 5985
      #     - 5986
      #   access: Allow
      #   priority: 1003
      #   direction: Inbound