---
- name: Create Azure Virtual Network
  hosts: localhost
  connection: local
  gather_facts: no

  collections:
    - azure.azcollection

  tasks:
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: ansible_RG
        #api_version: "2023-11-01"
        api_profile: latest
        name: myVirtualNetwork
        address_prefixes_cidr:
          - "10.1.0.0/16"
          - "172.100.0.0/16"
        dns_servers:
          - "127.0.0.1"
          - "127.0.0.2"
        tags:
          testing: testing