- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: "{{ location  }}"
  register: rg_result
  #ignore_errors: yes

- name: Debug output
  debug:
    msg: "{{ rg_result }}"